---
title: "Predicting Insurance Company Customer Behavior"
author: "Daniel Shang"
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r tidy=TRUE}
# The client is an insurance company that provides health insurance. It plans to launch a new vehicle insurance service and wants a model to predict whether the policy holders (customers) from past year will also be interested in vehicle insurance provided by the company. With a model, the company can plan its communication and marketing strategy to reach out to those customers, optimizing its business model and revenue.
```

```{r echo=TRUE, results='hide', warning=FALSE}
# Loaded the necessary packages and read the data from a CSV file
library(ggplot2)
library(dplyr)
library(ggthemes)
library(ggcorrplot)
library(mefa4)
library(e1071)
library(ROSE)
library(randomForest)
library(pROC)
library(caret)
data = read.csv('C:/Users/34527/Desktop/dataset.csv')
data_raw = read.csv('C:/Users/34527/Desktop/dataset.csv')
```

---------------------------------------------------------- Data cleaning ----------------------------------------------------------
```{r}
# Check if there is any missing data in the data set

for (i in 1:ncol(data)) {
  print(paste(colnames(data)[i], ':', sum(is.null(data[, i]))))
  print(paste(colnames(data)[i], ':', sum(data[, i] == 'NA')))
  print(paste(colnames(data)[i], ':', sum(data[, i] == 'N/A')))
  print(paste(colnames(data)[i], ':', sum(data[, i] == '')))
}
```

```{r tidy=TRUE}
# Transform categorical variables to dummy variables for easier analysis and better model performance

data[data[, 'Vehicle_Damage'] == 'Yes', 'Vehicle_Damage'] = 1
data[data[, 'Vehicle_Damage'] == 'No', 'Vehicle_Damage'] = 0
data[data[, 'Vehicle_Age'] == '< 1 Year', 'Vehicle_Age'] = 0
data[data[, 'Vehicle_Age'] == '1-2 Year', 'Vehicle_Age'] = 1
data[data[, 'Vehicle_Age'] == '> 2 Years', 'Vehicle_Age'] = 2
data[data[, 'Gender'] == 'Female', 'Gender'] = 0
data[data[, 'Gender'] == 'Male', 'Gender'] = 1
```

```{r tidy=TRUE}
# Manually remove the data points that is overly unrepresentative. The existence of these unrepresentative data points would abort the train/test split and other analysis

to_be_removed = data %>% count(Policy_Sales_Channel) %>%
  group_by(Policy_Sales_Channel) %>% filter(n < 5)
data = data[data$Policy_Sales_Channel %notin% to_be_removed$Policy_Sales_Channel, ]
data = data[, colnames(data)!= 'id']
```

--------------------------------------------------- Exploratory Data Analysis ------------------------------------------------------
```{r tidy=TRUE}
# A histogram showing the distribution of customer age. We can see that the customers of the company are relatively young. This could mean that the customer's average life-time value is high.

ggplot(data = data, aes(Age)) +
  geom_histogram(aes(y=..density..), fill="dodgerblue4",
                 color = 'white', alpha = 0.8, bins = 30) +
  geom_density() +
  labs(title = 'Histogram of Age') +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme_hc()
```


```{r tidy=TRUE}
# A histogram showing the distribution of annual premium customers currently pay. Although most customers' premium falls within a narrow range, there are some outliers.

ggplot(data = data, aes(Annual_Premium)) +
  geom_histogram(aes(y=..density..), fill="dodgerblue4", color = 'gray',
                 alpha = 0.8, bins = 50) +
  geom_density(adjust = 3) +
  labs(title = 'Histogram of Annual_Premium (in thousand)') +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme_hc() +
  scale_x_continuous(labels = function(x){x/10^3})
```

```{r tidy=TRUE}
# Summarize the annual premium data to better understand the distribution. From the 1st and 3rd quantile, we can tell that most customers pay a premium that falls within that range. But some customers are paying a premium as low as $2,630 or as high as $540,165

summary(data$Annual_Premium)
```

```{r tidy=TRUE}
# A histogram showing the distribution of customer vintage (the number of days they have been associated with the company). We can see that the customers are almost evenly distributed in terms of the vintage.

ggplot(data = data, aes(Vintage)) +
  geom_histogram(aes(y=..density..), fill="dodgerblue4",
                 color = 'white', alpha = 0.8, bins = 30) +
  geom_density() +
  labs(title = 'Histogram of Vintage') +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme_hc()
```

```{r tidy=TRUE}
# A bar chart showing the number of customers in each gender group. This shows that the customers are relatively evenly distributed in terms of their gender

ggplot(data = data, aes(Gender, fill = Gender)) +
  geom_bar(width = 0.5, alpha = 0.8, color = 'white', show.legend = FALSE) +
  labs(title = 'Bar chart of Gender') +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme_hc()
```

```{r tidy=TRUE}
# A bar chart showing the number of customers with and without a driver's license. We can see that only a tiny portion of customers do not have a driver's license. This indicates a great great start, because those who have a driver's license are likely to have a car, thereby likely to need vehicle insurance.

ggplot(data = data, aes(factor(Driving_License), fill = factor(Driving_License))) +
  geom_bar(width = 0.5, alpha = 0.8, show.legend = FALSE) +
  labs(title = 'Bar chart of Driving_License (in thousand)', x = 'Driving_License') +
  theme(plot.title = element_text(hjust = 0.5), legend.position = 'none') +
  scale_y_continuous(labels = function(y) {y/10^3}) +
  theme_hc()
```

```{r tidy=TRUE}
# A bar chart showing the number of customers within each region code. We can see that most customers of the company are in region with a code of 28 and 8. Therefore, the company may want to allocate more resources to these regions.

ggplot(data = data, aes(x = reorder(Region_Code, Region_Code,
          function(x) - length(x)), fill = factor(Region_Code))) +
  geom_bar(alpha = 0.8, color = 'white', show.legend = FALSE) +
  labs(title = 'Bar chart of Region_Code', x = 'Region_Code') +
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.3)) +
  theme_hc()
```

```{r tidy=TRUE}
# A bar chart showing the number of customers who are and are not previously insured. We can see that more customers are not previously insured than those who are previously insured. This may be a good thing, because less previously insured customers could convert to more current need for the new vehicle insurance.

ggplot(data = data, aes(factor(Previously_Insured), fill = factor(Previously_Insured))) +
  geom_bar(width = 0.5, alpha = 0.8, color = 'white', show.legend = FALSE) +
  labs(title = 'Bar chart of Previously_Insured', x = 'Previously_Insured') +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme_hc()
```

```{r tidy=TRUE}
# A bar chart showing the count of customers with a vehicle that falls into each of the three vehicle age groups. We can see that most customers have a vehicle aged 2 or less years.

ggplot(data = data, aes(factor(Vehicle_Age, ordered = TRUE,
      levels = c('0', '1', '2')), fill = factor(Vehicle_Age))) +
  geom_bar(width = 0.5, alpha = 0.8, color = 'white', show.legend = FALSE) +
  labs(title = 'Bar chart of Vehicle_Age', x = 'Vehicle_Age') +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme_hc()
```

```{r tidy=TRUE}
# A bar chart showing the number of customers with and without their vehicle been damaged. We can see that slighly more customers have their vehicle damaged before. This indicates that the company should be careful about pricing.

ggplot(data = data, aes(Vehicle_Damage, fill = Vehicle_Damage)) +
  geom_bar(width = 0.5, alpha = 0.8, color = 'white', show.legend = FALSE) +
  labs(title = 'Bar chart of Vehicle_Damage') +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme_hc()
```

```{r tidy=TRUE}
# A bar chart showing the number of customers within each policy sales channel. Similar to the distribution of region code, most customers have a policy sales channel of 152, 26, and 124. Based on this information, the company may plan its resources accordingly.

data %>%
  ggplot(aes(x = reorder(factor(Policy_Sales_Channel),
    Policy_Sales_Channel, function(x) -length(x)),
    fill = factor(Policy_Sales_Channel))) +
  geom_bar(alpha = 0.8, color = 'white', show.legend = FALSE) +
  labs(title = 'Bar chart of Policy_Sales_Channel (High to low in thousand)',
    x = 'Policy_Sales_Channel') +
  theme(axis.text.x = element_text(hjust = 1, angle = 90, vjust = 0.3, size = 7.5)) +
  scale_y_continuous(labels = function(y) {y/10^3}) +
  theme_hc()
```

```{r tidy=TRUE}
# A bar chart showing the count of customers' response. We can see that most customers are not interested in the vehicle insurance. The plot distribution indicates a huge data imbalance. We will handle this later because, if we train the model using the original data, the resulting model will focus much on predicting the customer response with a 0 value.

ggplot(data = data, aes(factor(Response), fill = factor(Response))) +
  geom_bar(stat = 'count', width = 0.5, alpha = 0.8, color = 'white',
      show.legend = FALSE) +
  labs(title = 'Bar chart of customer response', x = 'Response',
      y = 'count (in thousand)') +
  scale_y_continuous(labels = function(y) {y / 1000}) +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme_hc()
```

```{r tidy=TRUE}
# A stacked bar chart showing, within each customer response group, what percentage of customers is male and female. Although we can see that male customers are more likely to respond to the new insurance, the percentage difference does not seem to be statistically significant

ggplot(data, aes(factor(Response), fill = factor(Gender))) +
  geom_bar(width = 0.5, alpha = 0.8, position = 'fill', color = 'white') +
  scale_y_continuous(labels = scales::percent) +
  labs(x = 'Customer response', title = 'Customer response combined with gender') +
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme_hc()
```

```{r tidy=TRUE}
# A stacked bar chart showing, within each customer response group, what percentage of customers have or do not have a driver's license. Since most customers have a driver's license, the pink part is invisible

ggplot(data, aes(x = factor(Response), fill = factor(Driving_License))) +
  geom_bar(width = 0.5, alpha = 0.8, position = 'fill', color = 'white') +
  scale_y_continuous(labels = scales::percent) +
  labs(x = 'Customer response', 
       title = 'Customer response combined with drivering license') +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme_hc()
```

```{r tidy=TRUE}
# A stacked bar chart showing, within each customer response group, what percentage of customers are previously insured. We can see that more previously uninsured customers responded to the new vehicle insurance. However, those previously insured show no interest in the vehicle insurance. This already indicates that we should focus more on those customers who are not insured previously.

ggplot(data = data, aes(factor(Response), fill = factor(Previously_Insured))) + 
  geom_bar(width = 0.5, alpha = 0.8, position = 'fill', color = 'white') + 
  scale_y_continuous(labels = scales::percent) + 
  labs(x='Customer response', title = 'Customer response combined with previously insured') +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme_hc()
```

```{r tidy=TRUE}
# A stacked bar chart showing, within each customer response group, what percentage of customers have their vehicle damaged before. We can see those most customers who are interested in the vehicle insurance have their vehicles been damaged before. This indicates that the company should be careful and conservative about pricing, because the new customers of the vehicle insurance are probably going to get into accidents again.

ggplot(data, aes(x = factor(Response), fill = factor(Vehicle_Damage))) +
  geom_bar(width = 0.5, alpha = 0.8, position = 'fill', color = 'white') +
  scale_y_continuous(labels = scales::percent) +
  labs(x = 'Customer response', title = 'Customer response combined with Vehicle_damage') +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme_hc()
```

```{r tidy=TRUE}
# A stacked bar chart showing, within each customer response group, what percentage of customers have a vehicle with an age below one year, from one to two years, and over two years respectively

ggplot(data, aes(x = factor(Response), fill = factor(Vehicle_Age))) +
  geom_bar(width = 0.5, alpha = 0.8, position = 'fill', color = 'white') +
  scale_y_continuous(labels = scales::percent) +
  labs(title = 'Customer response combined with vehicle age') +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme_hc()
```

```{r tidy=TRUE}
# A density plot showing how customers' ages are distributed within each response group. The plot indicates that older customers are more likely to be interested in the vehicle customers.

ggplot(data, aes(x = Age, fill = factor(Response))) +
  geom_density(alpha = 0.8) +
  labs(title = 'Customer response by age') +
  scale_y_continuous(labels = scales::percent) +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme_hc()
```

```{r tidy=TRUE, warning=FALSE}
# A histogram showing how customers' annual premiums are distributed within each response group. The plot shows somewhat similar distributions of annual premium paid for the two groups of customers.

ggplot(data, aes(x = Annual_Premium, fill = factor(Response))) +
  geom_histogram(alpha = 0.8, color = 'black') +
  geom_density() +
  labs(title = 'Customer response by annual premium paid (0 - 100K)',
       x = 'Annual_Premium (in thousand)') +
  scale_x_continuous(labels = function(x) {x / 1000}) +
  theme(plot.title = element_text(hjust = 0.5)) +
  xlim(0, 100000) +
  theme_hc()
```

```{r tidy=TRUE}
# A density plot showing how customers' vintages are distributed within each response group. We can see that customer groups with different response to the new insurance are similar in their vintage. In other words, solely looking at a customer's vintage does not seem to tell us anything about his/her response. 

ggplot(data, aes(Vintage, fill = factor(Response))) +
  geom_density(alpha = 0.8) +
  scale_y_continuous(labels = scales::percent) +
  labs(title = 'Customer response by vintage') +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme_hc()
```

```{r tidy=TRUE}
# A density plot showing how customers of different response group are distributed within the country. We can see that, in most regions, more customers are not interested in the insurance. However, those customers in the region with code around 29 shows great interest. With these, the company can allocate its resources accordingly to target them.

ggplot(data, aes(x = Region_Code, fill = factor(Response))) +
  geom_density(alpha = 0.8) +
  scale_y_continuous(labels = scales::percent) +
  labs(title = 'Customer response by region code') +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme_hc()
```

```{r tidy=TRUE}
# A density plot showing how customers within each response group are distributed among different policy sales channel. We can see that, although there are many unique policy sales channel, most customers falls in a few of them. Additionally, most customers that falls under sales channel around 150 are much more likely to be interested in the insurance. With this information, the company can allocate its resources accordingly.

ggplot(data, aes(x = Policy_Sales_Channel, fill = factor(Response))) +
  geom_density(alpha = 0.8) +
  scale_y_continuous(labels = scales::percent) +
  labs(title = 'Customer response by policy sales channel') +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme_hc()
```

```{r tidy=TRUE}
# A correlation matrix showing the correlation between each pair of the variables. We can see that some variables are highly correlated. In this case, we may have to consider removing certain variables while modeling or using interaction.

data_matrix = data
for (i in 1:ncol(data_matrix)) {
  data_matrix[, i] = as.numeric(data_matrix[, i])
}

ggcorrplot(cor(data_matrix), method = 'square', type = 'full', lab = TRUE, 
  ggtheme = theme_void, lab_size = 2.5, outline.color = 'black', 
  color = c('blue', 'white', 'red'), title = 'Correlation matrix') +
  theme(plot.title = element_text(hjust = 0.5))
```

```{r tidy=TRUE}
# Based on the EDA, we can see that there are many values under the 'Region_Code' variable. Since most of them only occurred a few times, and most rows have certain region code, it may be a good idea to leave those frequently occurred region code as they are, and group the rest into a big group. Doing so may sacrifice a little model accuracy, but can boost the modeling efficiency very much. Some models, such as random forest, cannot even handle that many distinct categorical values. With these, I leave the top 4 region codes as they are in the original data, while group all other region codes into a big group called 'region_group'  

region_code_group = data %>% count(Region_Code) %>% arrange(desc(n)) %>%
  slice_max(n, n = 4) %>% select(Region_Code)
data[!(data$Region_Code %in% region_code_group$Region_Code), 'Region_Code'] = 'region_group'
```

```{r tidy=TRUE}
# Based on the same logic, I leave the top 4 policy sales channel as they are in the original dataset, while group all others into a big group called 'channel_group'

policy_group = data %>% count(Policy_Sales_Channel) %>% arrange(desc(n)) %>%
  slice_max(n, n = 4) %>% select(Policy_Sales_Channel)
data[!(data$Policy_Sales_Channel %in% policy_group$Policy_Sales_Channel), 
     'Policy_Sales_Channel'] = 'channel_group'
```

---------------------------------------------------- Logistic Regression Model ----------------------------------------------------
```{r}
# Before building the model, we convert the data that should not be treated like numeric variable to factor, ensuring proper modeling

data[, 'Response'] = as.factor(data[, 'Response'])
data[, 'Gender'] = as.factor(data[, 'Gender'])
data[, 'Driving_License'] = as.factor(data[, 'Driving_License'])
data[, 'Region_Code'] = as.factor(data[, 'Region_Code'])
data[, 'Previously_Insured'] = as.factor(data[, 'Previously_Insured'])
data[, 'Vehicle_Damage'] = as.factor(data[, 'Vehicle_Damage'])
data[, 'Policy_Sales_Channel'] = as.factor(data[, 'Policy_Sales_Channel'])
```

```{r tidy=TRUE}
# Randomly assign 80% of data to the training set and train the logistic regression model using data. Then, test the model using the 20% data left to check the prediction accuracy. Also, during the EDA process, we see that the target variable is imbalanced. This means that if we use the original data to train the model, the resulting model will target much on predicting those customers who are not interested in the insurance (those with a response of 0). To solve the data imbalance problem, I used a technique called over sampling. What it does is that the technique randomly sample the response that is under represented, and increase its occurrence until the number of occurrence of the two responses equal to each other. This way, the model will have a better performance predicting the outcome of our interest.

set.seed(123)
indices = sample(nrow(data), 0.8 * nrow(data))
train_set = data[indices, ]
test_set = data[-indices, ]

train_set = ovun.sample(Response ~ ., data = train_set, method = 'over', N = 535112)$data
```

```{r tidy=TRUE}
# Build a logistic regression model based on previous analysis

glm1 = glm(Response ~ Gender + Age * Vehicle_Age * Policy_Sales_Channel +
             Driving_License + Region_Code +
             Previously_Insured * Vehicle_Damage +
             Annual_Premium + Vintage,
          data = train_set,
          family = "binomial")
summary(glm1)
```

```{r tidy=TRUE, warning=FALSE}
# Setting a proper threshold, we get an overall out of sample prediction accuracy of 87.7%.

mean(ifelse(predict(glm1, test_set, type = 'response') > 0.91, 1, 0) == test_set$Response)
```

```{r tidy=TRUE}
# Here we use a visualization tool called ROC curve. It provides a way to better understand the model's ability to distinguish between 0 and 1 target variable

roc1 = roc(test_set$Response, predict(glm1, test_set, type = 'response'))
plot(roc1, col = 'blue')
```

```{r tidy=TRUE}
# Calculate the area under the ROC curve. The closer the area is to one, the better the model performs. Here, we get 85.29% as our AUC.

auc(roc1)
```

--------------------------------------------------------- Random Forest --------------------------------------------------------
```{r tidy=TRUE}
# Different models have different fundamental logic. Here, we use a random forest model to see how it performs in predicting the target response

rf = randomForest(Response ~ ., data = train_set, ntree = 250)
print(rf)
```

```{r tidy=TRUE}
# A confusion matrix shows how the random forest model performs. We can see that, although the overall accuracy is 71.25%, random forest does a very good job predicting the target variable that we are interested in (predicting customers who are interested in the insurance). How to choose between two models depends on our goal of building the model. Given our interest, we may want to use random forest for predicting purpose.

confusionMatrix(predict(rf, test_set), test_set$Response)
```
